module.exports = [
{
    title: "Gameplay",
    help: "In Kings of Chaos, you are in command of an army of either humans, elves, dwarves, orcs, or undead.\
           The aim of the game is to strengthen your army to attack enemy warlords and take their gold!\
           Players are ranked so you can see how your forces stack up to everyone else.",
    sections: [
        {
            title: "Build Your Army",
            help: "To build up your attack and defense strength, you must recruit soldiers and equip them with weapons.\
                   You may also hire mercenaries or train your soldiers. To recruit soldiers you must have people click\
                   on your unique link (you can find this in your Command Center). Each time you recruit an additional soldier,\
                   your attack and defense strength will increase slightly, as will the amount of gold you receive per turn.\
                   Also, for every two recruits each of your officers gets, you will receive an additional soldier!\
                   The number of officers you can have is unlimited, so the more people who sign up to be your officer\
                   the faster you can build your army.\
                   In addition to those soldiers generated by unique link clicks, you can choose to conscript soldiers\
                   - once a day you will recruit a number of soldiers determined by your current 'unit production' value.\
                   This value can be upgraded on the Training page."
        },
        {
            title: "Trained Soldiers",
            help: "To train your soldiers, use the Training section. Soldiers can be trained to be specialists\
                   in either attack or defense - whichever you choose, they will boost that ranking further,\
                   while ceasing to contribute to the other ranking. You can also train soldiers to become spies or sentries,\
                   which will be discussed in more detail later. In this case they cease to contribute to your attack/defense strength\
                   and the amount of gold you get per turn, as instead they are being kept in readiness\
                   for any covert missions you may choose to send them on."
        },
        {
            title: "Mercenaries",
            help: "You can hire mercenaries on the Mercenaries page, but only up to a strength of 25% of your total force\
                   - so for every 3 normal soldiers you gain, you can hire one more mercenary. Mercenaries\
                   contribute to your attack or defense strength, but do not contribute to the amount of gold you gain each turn."
        },
        {
            title: "Weapons",
            help: "Weaponry can be purchased (and repaired, sold or scrapped) on the Armory page.\
                   For each race there are various weapons available for both attacking and defending,\
                   becoming increasingly expensive as they become more effective. The exact strength of each weapon\
                   in your armory is dependent upon its state of repair (weapons become damaged during battles and must\
                   be repaired to remain fully effective), and also your level of siege technology and fortifications.\
                   Higher levels of siege technology and fortifications raise the strength of every single weapon you possess,\
                   so they are well worth upgrading. You can upgrade your siege and fortification levels on the Command Center page."
        },
        {
            title: "Spies and Sentries",
            help: "Covert Action is a general term for your Spy and Sentry ratings. Your force of spies becomes more powerful\
                   by training soldiers to be spies. Every spy you train increases your spy strength, and therefore helps you move up in spy ranking.\
                   Also, if you conduct many espionage missions spies will sometimes get caught, so you will need to replace them.\
                   If your spy rating is high, you will be able to see more players' gold on the battlefield without having to spy on them.\
                   Your force of sentries becomes more powerful by training soldiers to be sentries. Every sentry you train increases your sentry rating.\
                   The higher your sentry rating, the harder it is for other players to see your gold on the battlefield, spy on you or sabotage your weapons.\
                   If you invest in spies or sentries you should upgrade your covert skill when you can. Upgrading applies to your	entire force of spies and sentries.\
                   Upgrading covert skill, training spies and training sentries can all be done one the Training page."
        },
        {
            title: "Races",
            help: "Each race in Kings of Chaos has a particular area in which they excel.\
                   These can work to your advantage in gaining higher rankings, so it is worth considering them before choosing your race.<br />\
                   Current TBG (Turn-based gold) by race for all soldiers and covert troops:\
                       <ul><li>Elves, Orcs, and Undead: Untrained, trained attack, and trained defense soldiers earn 1 gold per turn.<br />\
                           Soldiers trained into covert troops (spies and sentries) earn 0.1 gold per turn.</li>\
                       <li>Dwarves: Untrained, trained attack, and trained defense soldiers earn 1.15 gold per turn.<br />\
                           Soldiers trained into covert troops (spies and sentries) earn 0.115 gold per turn.</li>\
                       <li>Humans: Untrained, trained attack, and trained defense soldiers earn 1.3 gold per turn.<br />\
                           Soldiers trained into covert troops (spies and sentries) earn 0.13 gold per turn.</li></ul>",
            sections: [
                {
                    title: "Humans",
                    help: "Humans earn 30% more gold each turn than the other four races.\
                           Since this can be used for just about anything, it is very flexible. Humans also have a 35% spy bonus."
                },
                {
                    title: "Elves",
                    help: "Elves are 45% better at recon (spying) and sabotage than any other race.\
                           This can be a great advantage when spying on or sabotaging other people's armies.\
                           Elves also have a 70% casualty bonus so they lose fewer soldiers when attacked."
                },
                {
                    title: "Orcs",
                    help: "Orcs attack with 35% more strength than the other races.\
                           The advantages to this are obvious, giving you a much better chance of defeating other armies in combat.\
                           Orcs also have a 20% defense bonus that makes it more likely that they will withstand enemy attacks and keep their gold."
                },
                {
                    title: "Dwarves",
                    help: "Dwarves are 40% stronger at defending than any other race.\
                          This makes it more likely that they will withstand enemy attacks, enabling them to keep their gold for themselves.\
                          Dwarves also have a 15% income bonus, which gives them more gold per turn than all races except Humans."
                },
                {
                    title: "Undead",
                    help: "Undead are 35% better at hiding their gold and defending against sabotage with their sentry bonus.\
                           They also lose 50% less soldiers when attacked making this a good protective race if you can't spend a lot of time on the game."
                }
            ]
        }
    ]
},
{
    title: "Quick Start Guide",
    help: "In Kings of Chaos, you are in command of an army of humans, elves, dwarves, orcs, or undead.\
           To be successful, you must manage your army and defeat your enemies. You must keep your troops in top condition and recover from losses.\
           A powerful army will be strong in all four aspects of the game: attacking, defending, spying, and sentry (counter-intelligence).\
           This makes it important to keep your forces and efforts relatively balanced in all these areas.",
    sections: [
        {
            title: "Recruiting",
            help: "<p>There are a number of ways to build your army and thus generate more gold and become more powerful:</p>\
                   <ul>\
                    <li>You can get people to click on your Unique Link, giving you an additional soldier each time it is clicked. \
                      <ul>\
                      <li>Logged-in players may click a given Unique Link up to 5 times per 24 hours.</li>\
                      <li>Friends who click your link and aren't logged in can click your link once per 24 hours.</li>\
                      </ul>\
                    </li>\
                    <li>If you tell friends about Kings of Chaos, you may recruit them as your officers:\
                      <ul>\
                      <li>If your friend clicks your Unique Link, then registers to play, you will receive a 50 soldier bonus!</li>\
                      <li>For every two soldiers your officers gain from their own Unique Links, you will gain an extra soldier for free!</li>\
                      </ul>\
                    </li>\
                    <li>Finally, you may buy mercenaries - soldiers that will fight for you but will not generate extra gold.</li>\
                    </ul>"
        },
        {
            title: "Command Center",
            help: "The Command Center is where you can see a broad outline of your forces.\
                   <ul>\
                      <li>Your Recruiting Link is found at the top of the Command Center. This is the primary method many players use to build their armies. Give this link to your friends to recruit them as your officers, which quickly grows your army through signup bonuses and trickle-down from their own clicking.</li>\
                        <li>User Info shows your general contact information.</li>\
                        <li>Military Overview Shows you general military stats, such as what your siege level is at and what fortifications you have. It also shows you how much gold you have and how much you are generating.</li>\
                        <li>Officers that you may have show up under this heading. Officers help build your army, and you may also choose to work with them as close allies.</li>\
                        <li>Military Effectiveness shows you your Attack, Defense, Spy, and Sentry ratings, as well as how you are ranked against other KOC players in these categories. This section shows you how well you are doing and how you stack up to other players in each aspect of the game.</li>\
                        <li>Personnel shows you how your forces are distributed.</li>\
                        <li>Previous Logins gives you the IP addresses and times of the last five logins to your account.</li>\
                        <li>Preferences is where you go to modify the setting on your account. Be very careful in this section - many of the changes here cannot be undone.</li>\
                    </ul>"
        },
        {
            title: "Attack",
            help: "When you wish to venture out beyond the safety of your fortifications, click the Attack button.\
                   Here, you will view the Battlefield, a listing of other players ranked near you.\
                   Players in yellow are online and those in green are not currently signed into the game.\
                   If you have previously reconned a player, you will see an eye in the first column which will link you to your intelligence log when clicked.\
                   The amount of gold in a player's treasury will be displayed if your Spy Rating is much larger than the opponent's Sentry Rating.\
                   You can page through the battlefield and search for other armies to attack or spy on.\
                   Once you click on a player's name you will see their User Stats, where you can see basic info about the player,\
                   any officers the player has, and you can recognize the player as friend, neutral, enemy, alliance member,\
                   or ignored if you wish to ignore all messages from them. From the User Stats panel you can choose to send a personal message,\
                   or conduct an attack, recon, or sabotage mission.<br />\
                   <ul>\
                	<li>Attack Mission - If you attack successfully, you will steal a portion of the enemy's available gold based on the damage you inflicted and the relative sizes of your armies. There is also a chance that you or your opponent will suffer casualties, based on army size and damage inflicted. The actual damages/repairs are shown on your armory page and not in the attack log. The casualties are listed with mercenaries and soldiers under \"your losses\" and any covert (spy or sentry) losses are shown in the \"details\" of the attack log.</li>\
                	<li>Reconnaissance Mission - You can conduct Recon missions to view info about an opponent's fortifications and forces. The chance that the mission is a success is dependant on the overall strength of the spies you send, as well as the enemy's Sentry Rating. If the mission is not a success you will no longer lose a portion of the spies you sent. There are a maximum of 10 recons permitted on a specific target per 24 hours.</li>\
                	<li>Sabotage Mission - If your opponent has overwhelming defense or has been relentlessly assaulting you, perhaps you may choose to engage in sabotage. In these missions, when you send a number of spies you specify what type and quantity weapons you want to try to sabotage. If your spies make it past enemy sentries they will attempt to sabotage part of the enemy's armory. If you attempt to sabotage too much of the enemy's armory the sabotage will likely fail, and no sabotage mission is guaranteed to be successful.  If you fail in a sabotage mission, you may lose a portion of your spies and even some of the tools they carry. While there is no limit on the number of sabotage missions you may attempt, you are allowed a maximum of 10 successful sabotage turns against a player per 24 hours.</li>\
                	<li>Personnel and Military Effectiveness - When you are preparing to attack, you are also shown your army stats again so you can make sure you want to go through with the mission, and in the case of covert missions, how many spies you have to dedicate to the task. In general, if your opponent has a larger army TFF (total fighting force) than yours, you will steal more of their gold as a reward.</li>\
                   </ul>"
        },
        {
            title: "Attack Log",
            help: "Here you can see details of ingoing and outgoing attacks.\
                   This can be a very useful way to see how much offensive and defensive damage you do on average,\
                   who you need to try to get protection from, or what armies you have had success with in the past.\
                   In your attack log you will see Attacks on You and Attacks on Others,\
                   and you will be able to page through the attacks if there are too many to fit on one screen."
        },
        {
            title: "Armory",
            help: "Your Armory is where you keep track of your weapons, and keep them in fighting condition.<br />\
                   <ul>\
                	<li>Current Weapon Inventory is where you see the weapons you currently own, as well as their strengths. If your weapons are damaged, it is cheaper to repair them than to buy new ones. You can also sell weapons at a reduced rate for gold.</li>\
                	<li>Current Tool Inventory is where you see the tools for sentries and spies that you currently own. You can also sell spy and sentry tools at a reduced rate. Sabotaged tools will no longer be in your armory as they are removed when sabotaged. (Your spies are more observant than your regular soldiers!)</li>\
                	<li>Buy Weapons allows you to purchase new weapons for your forces. In general, the more expensive a weapon is, the stronger it is. Some weapons are unique to your race, while others can be bought by anyone.</li>\
                	<li>Buy Tools allows you to purchase new tools for your spies and sentries, making them much more effective.</li>\
                	<li>Upgrade Fortifications is where you can strengthen your permanent defenses. This makes it much more difficult to be attacked successfully. Fortifications strengthen your defensive units as a whole.</li>\
                	<li>Upgrade Siege Technology allows you to purchase new technologies to attack your opponents. This strengthens your army as a whole.</li>\
                   </ul>"
        },
        {
            title: "Training",
            help: "<ul>\
                	<li>Personnel shows you how many soldiers, mercenaries, spies, sentries, etc you have.</li>\
                	<li>Train Your Troops allows you train your untrained soldiers to be attack or defense specialists, or to be skilled in the subterfuge of spies and sentries. Here you can also revert any attack or defense soldiers to regular units.</li>\
                	<li>Upgrade Covert Skill makes all of your spies and sentries more powerful - it is a very effective way to increase the power of your covert forces.</li>\
                	<li>Upgrade Unit Production allows you to conscript soldiers from the local populace - each day this number of soldiers will join your forces.</li>\
                   </ul>"
        },
        {
            title: "Intelligence",
            help: "Your intelligence files are similar to your attack log, but they give you details of covert missions from and against you.\
                   Here you see details of Intercepted Intelligence Operations as well as Intelligence Files from missions you have conducted.\
                   Not all missions are intercepted and therefore you will not see everyone who has reconned you or sabotaged you.\
                   Not all recons or sabotages done by you were intercepted either, this is called \"ghosting\".\
                   When no missions are intercepted, that player has been \"ghosted\"."
        },
        {
            title: "Recruiting",
            help: "Recruiting is an effective way for you to build your army's morale, which eventually results in new recruits.\
                   When you recruit for another player by completing the CAPTCHA on the recruit page, your army's morale increases and they receive one soldier.\
                   When another player recruits for you, your army's morale drops, but you gain a soldier. Recruiting proceeds in this order:\
                   you, your friends, other members of your alliance, then finally any other users with positive morale (ordered by greatest morale).\
                   This means that the greater your morale, the quicker it will be converted into extra recruits.<br /><br />\
                   Only logged-in players can turn your army's morale into new soldiers.\
                   Non-logged-in friends can still increase your army size by clicking your unique link, found in your Command Center."
        },
        {
            title: "Mercenaries",
            help: "On this page you can see the details of your current troops, and you can hire mercenaries. Mercenaries can be hired as attack specialists,\
                   defence specialists, or all-purpose troops. Once hired, they cannot be retrained. Mercenaries cannot be spies,\
                   and do not contribute to the amount of gold you receive each turn, but they do boost your attack and/or defence strength\
                   (depending on what type of training they have). Mercenaries become available for hire randomly and their numbers are limited\
                   so there are often none available shortly after that. You can only have 25% of your army consisting of mercenaries.\
                   Mercenaries are added to your total fighting force (TFF) and they have to die to lower your TFF."
        },
        {
            title: "Buddy List",
            help: "The buddy list can be used to keep track of people who you recognize as either neutral, friend, enemy, ignored or alliance members.\
                   You can recognize players via the drop down on their stats page. You are allowed a maximum of 180 players per buddy type.\
                   (Hopefully that's 180 friends, not 180 enemies!)"
        },
        {
            title: "Message",
            help: "The Send Message page is accessed from a user's stats page, by clicking on the Send Message button.\
                   You are then presented with a page which has areas for you to enter a subject and a message to be sent to that user.<br /><br />\
                   When someone has sent you a message in this fashion, you will notice the message indicator beneath the main menu will change\
                   to show how many new messages you have waiting for you. To read them, simply click on the red number and you will be taken to the Read Messages page.\
                   The most recent message will appear at the top of the page, with older messages beneath it in reverse order of receipt.\
                   You can use the buttons on the right to Reply to or Delete each message."
        }
    ]
},
{
    title: "Rules",
    help: "",
    sections: [
        {
            title: "Prohibited",
            help: "<ul>\
                      <li>Registering or having control of more than one account</li>\
                      <li>Sharing passwords with other people and logging into accounts that are not yours</li>\
                      <li>Posting links in the Kings of Chaos chat, Kings of Chaos forums, or anywhere it is against the policies</li>\
                      <li>Registering an email address that is not yours</li>\
                      <li>Registering more than one account, or transferring your account to someone else</li>\
                      <li>Advertising through PM or any other method, or sending unsolicited recruiting PMs</li>\
                      <li>Using any process which enables clicking beyond that which is intended by gameplay mechanisms</li>\
                      <li>Downloading any part of the Kings of Chaos website with any piece of software other than a web browser</li>\
                      <li>Using any process that automatically gets information from the website</li>\
                      <li>Using any process that automatically posts information to the website</li>\
                      <li>Using any process that combines multiple gameplay actions (attack, sabotage, etc) into one user action</li>\
                      <li>Accessing any part of the Kings of Chaos website via proxy</li>\
                      <li>Attempting to cause harm to the any of the Kings of Chaos servers</li>\
                      <li>Attempting in any way to circumvent the mechanisms set up to keep Kings of Chaos fair</li>\
                    </ul>"
        },
        {
            title: "Sharing your link",
            help: "<ul>\
                      <li>Post your link on message boards where it is allowed and is on-topic</li>\
                      <li>Email your link to your <b>friends</b> or send it to them on instant messenger</li>\
                      <li>Have people who are not signed into the game click your link</li>\
                      <li>Have your link in your AIM/MSN/ICQ etc. profile</li>\
                      <li>Post your link on a personal website</li>\
                    </ul>"
        }
    ]
},
{
    title: "Frequently Asked Questions",
    help: "",
    sections: [
        {
            title: "How much does this cost to play?",
            help: "Nothing. It's free. Kings of Chaos is completely supported by advertisers. Enjoy!"
        },
        {
            title: "How do I get a bigger and better army?",
            help: "Check the 'Recruiting' section in the Quick Start Guide"
        },
        {
            title: "How are rankings calculated?",
            help: "All players are ranked in each of the four categories of attack strength, defense strength, spy rating and sentry rating.\
                   These four rankings are added to give your overall ranking."
        },
        {
            title: "What are the siege, fortification, and unit production levels?",
            help: "We'd rather not say, and let you find out on your own =)"
        },
        {
            title: "What happened to all my stuff?",
            help: "A new age has begun! At the beginning of each Age, we reset everyone's weaponry and army size to give everyone a fresh start.\
                   Now is the time to rebuild and prove yourself better than those around you!"
        },
        {
            title: "Why am I loosing gold and soldiers?",
            help: "You are probably being attacked. Check your attack log to see who attacked you, how many soldiers they killed and how much gold they stole from you."
        },
        {
            title: "How come I'm not listed in the rankings?",
            help: "Ranks are only recalculated once every hour, so you will have to wait until rankings are generated to appear on the rankings page."
        },
        {
            title: "Why doesn't my rank improve when I get more weapons?",
            help: "Ranks are only recalculated once every hour, so you will have to wait to see how your ranking has been changed by upgrades or purchases."
        },
        {
            title: "How are Alliance Rankings calculated?",
            help: "Alliances are ranked by summing 1/(userrank+1) for every member of the alliance who has set that alliance to be their primary alliance.\
                   Top 10 Alliances are ranked by members' overall rank, Fiercest Alliances are ranked by members' Strike Action rank, etc."
        },
        {
            title: "It's hard to get people to click my link. Is there another way to gain recruits?",
            help: "The easiest way to gain recruits is to persuade friends to click your link, but you can also upgrade your Unit Production (on the Training page),\
                   and hire mercenaries to boost your army strength."
        },
        {
            title: "Why don't I ever kill any enemy soldiers?",
            help: "The bigger your army, the more casualties you are likely to suffer. Armies small enough will not usually suffer casualties\
                   because this would hurt the army much more."
        },
        {
            title: "How do I change my race?",
            help: "If you have played Kings of Chaos in a previous age, the first time you log in\
                   you will be asked to select the race you want to play for the rest of that age.\
                   If you are new you will choose your race when you register.\
                   You can change your race up to 3 times. After that, you cannot change race any more without resetting your account."
        }
    ]
},
{
    title: "Glossary",
    help: "",
    sections: [
        {
            title: "Age",
            help: "The length of the round, which varies but usually lasts roughly six months.\
                   Between ages, your army size, wealth, weapons, and race will be reset, giving you a chance to change races.\
                   You will, however, get to keep your officers."
        },
        {
            title: "Alliance",
            help: "Multiple warlords working together for a common goal, or just to have fun. You can find a list of alliances on the Kings of Chaos forums."
        }
        ,
        {
            title: "Armory",
            help: "The place to purchase weapons."
        }
        ,
        {
            title: "Army Size",
            help: "The number of recruits you have. This is the number of people who have clicked your link, plus a fraction of the army size of your officers.\
                   Determines the amount of money you get each turn."
        }
        ,
        {
            title: "Attack",
            help: "To attack someone, you use one attack turn. These attack turns are replaced at the rate of one every three hours,\
                   with a possible of 8 per 24 hours. You may store up to 50000 attack turns."
        }
        ,
        {
            title: "Attack Log",
            help: "A log of everyone who you have attacked recently, and anyone who has attacked you recently."
        }
        ,
        {
            title: "Attack Turns",
            help: "Attack turns are one of the crucial resources in the game. You use attack turns to pillage other armies and take their gold.\
                   You receive one attack turn every three hours, with a possible of 8 per 24 hours. You may store up to 50000 attack turns."
        }
        ,
        {
            title: "Battlefield (BF)",
            help: "The Attack button in the Menu Bar on the left side of the page takes you to the Battlefield, a listing of other players ranked near you.\
                   Players in yellow are online and those in green are not currently signed into the game. If you have previously reconned a player,\
                   you will see an eye in the first column that will link you to your intelligence log when clicked.\
                   The amount of gold in a player's treasury will be displayed if your Spy Rating is much larger than the opponent's Sentry Rating.\
                   You can page through the battlefield and search for other targets."
        }
        ,
        {
            title: "Blackpowder Missle (BPM)",
            help: "Currently the strongest attacking weapon."
        }
        ,
        {
            title: "Clan",
            help: "See Alliance"
        }
        ,
        {
            title: "Command Center",
            help: "Clicking here allows you to view your own stats, including stats that are not available to everyone else."
        }
        ,
        {
            title: "CAPTCHA",
            help: "Completely Automated Public Turing test to tell Computers and Humans Apart. The random images try to deter cheating."
        }
        ,
        {
            title: "Casualties",
            help: "Normal losses suffered in the course of attacking and defending.\
                   If your army is not very big, you will probably not suffer very many casualties, if any."
        }
        ,
        {
            title: "Commander",
            help: "The person you are under as an officier, if any. You can change or ditch your commander up to 5 times"
        }
        ,
        {
            title: "Defensive Action (DA)",
            help: "The total defending power of your army. Based on your trained defense soldiers, untrained soldiers, mercenaries, their weapons, and your Fortifications."
        }
        ,
        {
            title: "Dwarves",
            help: "One of the races in Kings of Chaos. Dwarves get a 40% defense bonus, protecting them when attacked, and a 15% income bonus."
        }
        ,
        {
            title: "Elves",
            help: "One of the races in Kings of Chaos. Elves get a 45% spy bonus, making them extremely good at recon and sabotage."
        }
        ,
        {
            title: "Fortifications",
            help: "These contribute to the strength of all your defense troops and weaponry. The basic fortification is \"Camp\" - they can be upgraded in the Armory."
        }
        ,
        {
            title: "Ghosted/ghosting",
            help: "Sabotage or recon missions that are successful and were not intercepted so that the warlord who was sabotaged\
                   or reconned has no knowledge or record of the mission."
        }
        ,
        {
            title: "Gold",
            help: "The basic monetary unit of Kings of Chaos. Spend gold at the Armory to purchase weapons."
        }
        ,
        {
            title: "Humans",
            help: "One of the races in Kings of Chaos. Humans get a 30% income bonus each turn, as well as a 35% spy bonus."
        }
        ,
        {
            title: "Intelligence",
            help: "A list of other warlords whom you have spied on or sabotaged, or from whom you have intercepted spies.\
                   NOTE: Not all missions are intercepted. As they are not recorded, they are called \"ghosted\"."
        }
        ,
        {
            title: "Invisibility Shield (IS)",
            help: "Currently the strongest defensive weapon."
        }
        ,
        {
            title: "Losses",
            help: "See Casualties"
        }
        ,
        {
            title: "Profile",
            help: "An in-depth description of a warlord, showing stats useful to know when deciding whether to attack them."
        }
        ,
        {
            title: "Officer",
            help: "One of the people who visited your link and decided to join up. They help build your army."
        }
        ,
        {
            title: "Orc",
            help: "One of the races in Kings of Chaos. Orcs have a 35% attack bonus and a 20% defense bonus, making them fearsome in battle."
        }
        ,
        {
            title: "Race",
            help:  "The type of warlord someone is. There are five races: Humans, Elves, Dwarves, Undead, and Orcs."
        }
        ,
        {
            title: "Rank",
            help:  "Rank shows how well you are doing compared to all other armies in Kings of Chaos.\
                    Your rank is computed by adding your Strike Action, Defensive Action, Spy Rating, and Covert Rating.\
                    The person with the smallest sum will be ranked first, next smallest is second, etc.\
                    To achieve a high rank you must have good ratings in all four areas of the game."
        }
        ,
        {
            title: "Reconaissance (Recon)",
            help:  "Using spies to learn about another warlord's personnel, weapons, and military effectiveness."
        }
        ,
        {
            title: "Recruit Link",
            help:  "See Unique Link."
        }
        ,
        {
            title: "Sabotage",
            help:  "Using spies to disable another warlord's weapons so they cannot be used in combat.\
            If any of your weapons have been sabotaged you won't know until you try to use them in combat.\
            Sentry and Spy tools that have been sabotaged are removed from your armory immediately.\
            Strike Action weapons can be sold and repurchased if sabotaged unless you first attack another warlord, breaking them.\
            Defense weapons can only be sold and repurchased if another warlord has not broken them by attacking you.\
            Broken weapons are removed immediately from your armory."
        }
        ,
        {
            title: "Sentry Rating",
            help:  "The strength of your counter-espionage forces. Based on the number of sentries in your army, and your spy level."
        }
        ,
        {
            title: "Siege Technology",
            help:  "This contributes to the overall strength of all your attack troops and weaponry. The basic is \"None\" - it can be upgraded in the Armory."
        }
        ,
        {
            title: "Spy Rating",
            help:  "The strength of your espionage forces. Based on the number of spies in your army, and your spy level."
        }
        ,
        {
            title: "Spy Skill/Spy Level",
            help:  "The skill level of each individual spy and sentry in your army. Upgrading strengthens all of your spies and sentries."
        }
        ,
        {
            title: "Stats Link",
            help:  "Can be found by clicking yourself on the attack page (battlefiled or BF) and checking in the address bar of your browser."
        }
        ,
        {
            title: "Strike Action (SA)",
            help:  "The total offensive power of your army.\
                    Based on your trained attack soldiers, untrained soldiers, mercenaries, their weapons, and your Siege Technology."
        }
        ,
        {
            title: "Subofficer",
            help:  "One of your officers' officers, or their officer, etc."
        }
        ,
        {
            title: "Tool",
            help:  "Purchasing tools increases the effectiveness of your spies or sentries. You can buy tools in the Armory."
        }
        ,
        {
            title: "Total Fighting Force",
            help:  "The total number of your trained and untrained soldiers, plus any mercenaries you may have."
        }
        ,
        {
            title: "Turn",
            help:  "The basic unit of time in Kings of Chaos. Currently 30 minutes long."
        }
        ,
        {
            title: "Turn Based Gold (TBG)",
            help:  "The gold you get each turn. Your TBG is based on how many soldiers are in your army, with certain races getting income bonuses.\
                    Soldiers contribute most to your TBG. Spies and sentries contribute less to your TBG. Mercenaries do not contribute towards TBG."
        }
        ,
        {
            title: "Undead",
            help:  "One of the races in Kings of Chaos.\
                    Undead get a 35% sentry bonus and lose 50% fewer soldiers when attacked, making them a good protective race."
        }
        ,
        {
            title: "Unique Link / Unique ID",
            help:  "The link used to increase your army's TFF by clicking on it.\
                    Give this to people to click! If they sign up as your officer you'll receive a 50 soldier bonus,\
                    a bonus soldier for every two they get, and a helpful ally! This link is found in your Command Center."
        }
        ,
        {
            title: "Unit Production (UP)",
            help:  "Upgraded Unit Production allows you to augment your TFF (total fighting force) by a set amount of soldiers every day.\
            These soldiers will join your forces at the same time each day."
        }
        ,
        {
            title: "Vacation Mode (vmode)",
            help:  "An option to deactivate (suspend) your account for a length of time.\
                    Useful if you are going on a long trip and won't be able to play KoC during that time.\
                    Once you are in vacation mode you must wait until the time has elapsed before playing, so be careful.\
                    You receive no TBG (turn based gold), UP (unit production), recruit clicks or attack turns while in vacation mode.\
                    When your account comes out of vacation mode, you must wait until you are ranked before you can attack anyone."
        }
        ,
        {
            title: "Warlord",
            help:  "A player in Kings of Chaos."
        }
        ,
        {
            title: "Weapons",
            help:  "Offensive or defensive equipment for soldiers in your army.\
                    Attack weapons are only used when you attack, defense weapons are only used when you defend.\
                    You can only use as many weapons as you have soldiers, and you can buy weapons in the Armory.\
                    Your soldiers are not very effective without weapons."
        }
    ]
}
];